# Generated by Django 5.0.4 on 2026-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('general', 'General'), ('grado', 'Por grado'), ('seccion', 'Por sección')], default='general', max_length=10)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normal', max_length=12)),
                ('publicado', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comunicado',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='LecturaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lectura de comunicado',
            },
        ),
    ]
