# Generated by Django 5.0.4 on 2026-04-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0002_initial'),
        ('comunicados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='grados',
            field=models.ManyToManyField(blank=True, related_name='comunicados', to='asistencia.grado'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='secciones',
            field=models.ManyToManyField(blank=True, related_name='comunicados', to='asistencia.seccion'),
        ),
        migrations.AddField(
            model_name='lecturacomunicado',
            name='comunicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='comunicados.comunicado'),
        ),
        migrations.AddField(
            model_name='lecturacomunicado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lecturacomunicado',
            unique_together={('comunicado', 'usuario')},
        ),
    ]
