# Generated by Django 5.0.4 on 2026-04-02 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grado',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sección',
                'ordering': ['grado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('cerrada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesión de clase',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TokenQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Token QR',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('tardanza', 'Tardanza'), ('ausente', 'Ausente'), ('justificado', 'Justificado')], default='ausente', max_length=15)),
                ('hora_registro', models.DateTimeField(blank=True, null=True)),
                ('registrado_via_qr', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.alumno')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'ordering': ['-sesion__fecha'],
            },
        ),
    ]
