# Generated by Django 5.0.4 on 2026-04-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='asistencia.grado'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='asistencia.grado'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='asistencia.seccion'),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='asistencia.curso'),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_dictadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='asistencia.seccion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.sesionclase'),
        ),
        migrations.AddField(
            model_name='tokenqr',
            name='sesion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_qr', to='asistencia.sesionclase'),
        ),
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('grado', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('sesion', 'alumno')},
        ),
    ]
