# Generated by Django 5.0.4 on 2026-04-02 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salida_anticipada', 'Salida anticipada'), ('tardanza_justificada', 'Tardanza justificada'), ('ausencia_justificada', 'Ausencia justificada')], max_length=25)),
                ('motivo', models.TextField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('observacion_revision', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='asistencia.alumno')),
            ],
            options={
                'verbose_name': 'Permiso de salida',
                'verbose_name_plural': 'Permisos de salida',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
