# Generated by Django 5.0.4 on 2026-04-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permisos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permisosalida',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permisosalida',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
